# Load every static JoinMarket NG bash completion next to this file.
#
# The per-command scripts are generated by scripts/generate_completions.py and
# only need plain bash, so this loader deliberately does not depend on the
# bash-completion package (which is absent from the Docker images).
#
# Usage:
#   . /etc/bash_completion.d/jm-completions-loader.sh   # Docker images
#   . completions/jm-completions-loader.sh              # source checkout

_jm_completions_dir=$(dirname "${BASH_SOURCE[0]}")
for _jm_completion in "$_jm_completions_dir"/*.bash; do
    if [ -r "$_jm_completion" ]; then
        . "$_jm_completion"
    fi
done
unset _jm_completion _jm_completions_dir
