#compdef jm-maker

# Static completion for jm-maker
# Generated by scripts/generate_completions.py

_jm_maker() {
  local -a commands
  commands=(
    'start:Start the maker bot.'
    'generate-address:Generate a new receive address.'
    'config-init:Initialize the config file with default settings.'
  )

  _arguments -C \
    '1:command:->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'jm-maker commands' commands
      ;;
    args)
      case $words[1] in
        start)
          _arguments \
            '--mnemonic-file=[Path to mnemonic file]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase interactively]' \
            '--data-dir=[Data directory for JoinMarket files. Defaults to ~/.joinmarket-ng]:file:_files' \
            '--network=[Protocol network (mainnet, testnet, signet, regtest)]:choice:(mainnet testnet signet regtest)' \
            '--bitcoin-network=[Bitcoin network for address generation (defaults to --network)]:choice:(mainnet testnet signet regtest)' \
            '--backend-type=[Backend type\: descriptor_wallet | neutrino]: :' \
            '--rpc-url=[Bitcoin full node RPC URL]: :' \
            '--neutrino-url=[Neutrino REST API URL]: :' \
            '--min-size=[Minimum CoinJoin size in sats]: :' \
            '--cj-fee-relative=[Relative coinjoin fee (e.g., 0.001 = 0.1%)]: :' \
            '--cj-fee-absolute=[Absolute coinjoin fee in sats. Mutually exclusive with --cj-fee-relative.]: :' \
            '--tx-fee-contribution=[Tx fee contribution in sats]: :' \
            '--directory=[Directory servers (comma-separated host\:port)]: :' \
            '--tor-socks-host=[Tor SOCKS proxy host (overrides TOR__SOCKS_HOST)]: :' \
            '--tor-socks-port=[Tor SOCKS proxy port (overrides TOR__SOCKS_PORT)]: :' \
            '--tor-control-host=[Tor control port host (overrides TOR__CONTROL_HOST)]: :' \
            '--tor-control-port=[Tor control port (overrides TOR__CONTROL_PORT)]: :' \
            '--tor-cookie-path=[Path to Tor cookie auth file (overrides TOR__COOKIE_PATH)]:file:_files' \
            '--disable-tor-control[Disable Tor control port integration]' \
            '--onion-serving-host=[Bind address for incoming connections (overrides MAKER__ONION_SERVING_HOST)]: :' \
            '--onion-serving-port=[Port for incoming .onion connections (overrides MAKER__ONION_SERVING_PORT)]: :' \
            '--tor-target-host=[Target hostname for Tor hidden service (overrides TOR__TARGET_HOST)]: :' \
            '--fidelity-bond-locktime=[Fidelity bond locktimes to scan for]: :' \
            '--fidelity-bond-index=[Fidelity bond derivation index]: :' \
            '--fidelity-bond=[Specific fidelity bond to use (format\: txid\:vout)]: :' \
            '--no-fidelity-bond[Disable fidelity bond usage. Skips registry lookup and bond proof generation even when bonds exist in the registry.]' \
            '--merge-algorithm=[UTXO selection strategy\: default, gradual, greedy, random]: :' \
            '--dual-offers[Create both relative and absolute fee offers simultaneously. Each offer gets a unique ID (0 for relative, 1 for absolute). Use with --cj-fee-relative and --cj-fee-absolute to set fees for each.]' \
            '--log-level=[Log level]: :' \
            '--help[Show this message and exit]'
          ;;
        generate-address)
          _arguments \
            '--mnemonic-file=[Path to mnemonic file]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase interactively]' \
            '--network=[Protocol network]:choice:(mainnet testnet signet regtest)' \
            '--bitcoin-network=[Bitcoin network for address generation (defaults to --network)]:choice:(mainnet testnet signet regtest)' \
            '--backend-type=[Backend type]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--log-level=[Log level]: :' \
            '--help[Show this message and exit]'
          ;;
        config-init)
          _arguments \
            '--data-dir=[Data directory for JoinMarket files]:file:_files' \
            '--help[Show this message and exit]'
          ;;
      esac
      ;;
  esac
}

compdef _jm_maker jm-maker
