#compdef jm-taker

# Static completion for jm-taker
# Generated by scripts/generate_completions.py

_jm_taker() {
  local -a commands
  commands=(
    'coinjoin:Execute a single CoinJoin transaction.'
    'tumble:Run a tumbler schedule of CoinJoins.'
    'clear-ignored-makers:Clear the list of ignored makers.'
    'config-init:Initialize the config file with default settings.'
  )

  _arguments -C \
    '1:command:->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'jm-taker commands' commands
      ;;
    args)
      case $words[1] in
        coinjoin)
          _arguments \
            '--amount=[Amount in sats (0 for sweep)]: :' \
            '--destination=[Destination address (or '\''INTERNAL'\'' for next mixdepth)]: :' \
            '--mixdepth=[Source mixdepth]: :' \
            '--counterparties=[Number of makers]: :' \
            '--mnemonic-file=[Path to mnemonic file]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase interactively]' \
            '--network=[Protocol network for handshakes]:choice:(mainnet testnet signet regtest)' \
            '--bitcoin-network=[Bitcoin network for addresses (defaults to --network)]:choice:(mainnet testnet signet regtest)' \
            '--backend=[Backend type\: descriptor_wallet | neutrino]: :' \
            '--rpc-url=[Bitcoin full node RPC URL]: :' \
            '--neutrino-url=[Neutrino REST API URL]: :' \
            '--directory=[Directory servers (comma-separated)]: :' \
            '--tor-socks-host=[Tor SOCKS proxy host (overrides TOR__SOCKS_HOST)]: :' \
            '--tor-socks-port=[Tor SOCKS proxy port (overrides TOR__SOCKS_PORT)]: :' \
            '--max-abs-fee=[Max absolute fee in sats]: :' \
            '--max-rel-fee=[Max relative fee (0.001=0.1%)]: :' \
            '--fee-rate=[Manual fee rate in sat/vB. Mutually exclusive with --block-target.]: :' \
            '--block-target=[Target blocks for fee estimation (1-1008). Cannot be used with neutrino.]: :' \
            '--bondless-allowance=[Fraction of time to choose makers randomly (0.0-1.0)]: :' \
            '--bond-exponent=[Exponent for fidelity bond value calculation]: :' \
            '--bondless-zero-fee[For bondless spots, require zero absolute fee]' \
            '--select-utxos[Interactively select UTXOs (fzf-like TUI)]' \
            '--yes[Skip confirmation prompt]' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--config-file=[Config file path (decoupled from data dir). Defaults to <data-dir>/config.toml]:file:_files' \
            '--log-level=[Log level]: :' \
            '--help[Show this message and exit]'
          ;;
        tumble)
          _arguments \
            '--mnemonic-file=[Path to mnemonic file]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase interactively]' \
            '--network=[Bitcoin network]:choice:(mainnet testnet signet regtest)' \
            '--backend=[Backend type\: descriptor_wallet | neutrino]: :' \
            '--rpc-url=[Bitcoin full node RPC URL]: :' \
            '--neutrino-url=[Neutrino REST API URL]: :' \
            '--directory=[Directory servers (comma-separated)]: :' \
            '--tor-socks-host=[Tor SOCKS proxy host (overrides TOR__SOCKS_HOST)]: :' \
            '--tor-socks-port=[Tor SOCKS proxy port (overrides TOR__SOCKS_PORT)]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--config-file=[Config file path (decoupled from data dir). Defaults to <data-dir>/config.toml]:file:_files' \
            '--log-level=[Log level]: :' \
            '--help[Show this message and exit]'
          ;;
        clear-ignored-makers)
          _arguments \
            '--data-dir=[Data directory for JoinMarket files]:file:_files' \
            '--config-file=[Config file path (decoupled from data dir). Defaults to <data-dir>/config.toml]:file:_files' \
            '--help[Show this message and exit]'
          ;;
        config-init)
          _arguments \
            '--data-dir=[Data directory for JoinMarket files]:file:_files' \
            '--config-file=[Config file path (decoupled from data dir). Defaults to <data-dir>/config.toml]:file:_files' \
            '--help[Show this message and exit]'
          ;;
      esac
      ;;
  esac
}

compdef _jm_taker jm-taker
