#compdef jm-tumbler

# Static completion for jm-tumbler
# Generated by scripts/generate_completions.py

_jm_tumbler() {
  local -a commands
  commands=(
    'config-init:Initialize the config file with default settings.'
    'delete:Delete the on-disk plan for ``wallet_name``.'
    'plan:Build a tumbler plan for the given destinations and persist it.'
    'run:Execute the saved plan for a wallet to completion.'
    'status:Print the current plan for the given wallet.'
  )

  _arguments -C \
    '1:command:->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'jm-tumbler commands' commands
      ;;
    args)
      case $words[1] in
        config-init)
          _arguments \
            '--data-dir=[Data directory for JoinMarket files]:file:_files' \
            '--config-file=[Config file path (decoupled from data dir). Defaults to <data-dir>/config.toml]:file:_files' \
            '--help[Show this message and exit]'
          ;;
        delete)
          _arguments \
            '--wallet-name=[Wallet identifier; defaults to the mnemonic fingerprint]: :' \
            '--mnemonic-file=[Path to mnemonic file]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase interactively]' \
            '--yes[Skip confirmation prompt]' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--config-file=[Config file path (decoupled from data dir). Defaults to <data-dir>/config.toml]:file:_files' \
            '--log-level=[]: :' \
            '--help[Show this message and exit]'
          ;;
        plan)
          _arguments \
            '--destination=[External destination address (repeatable)]: :' \
            '--mnemonic-file=[Path to mnemonic file]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase interactively]' \
            '--wallet-name=[Wallet identifier for the plan file; defaults to the mnemonic fingerprint]: :' \
            '--network=[Bitcoin network]:choice:(mainnet testnet signet regtest)' \
            '--backend=[Backend type\: descriptor_wallet | neutrino]: :' \
            '--rpc-url=[Bitcoin full node RPC URL]: :' \
            '--neutrino-url=[Neutrino REST API URL]: :' \
            '--force[Overwrite an existing pending plan]' \
            '--seed=[Seed the plan builder RNG for reproducible schedules]: :' \
            '--maker-count-min=[Minimum counterparty count per CJ; defaults to settings.taker.counterparty_count]: :' \
            '--maker-count-max=[Maximum counterparty count per CJ; defaults to settings.taker.counterparty_count]: :' \
            '--mincjamount-sats=[Minimum CJ amount in sats]: :' \
            '--maker-sessions[]' \
            '--allow-few-destinations[Override the recommended minimum of 3 destinations. Intended for development and automated testing only\: fewer destinations expose users to pairwise re-aggregation heuristics.]' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--config-file=[Config file path (decoupled from data dir). Defaults to <data-dir>/config.toml]:file:_files' \
            '--log-level=[]: :' \
            '--help[Show this message and exit]'
          ;;
        run)
          _arguments \
            '--mnemonic-file=[Path to mnemonic file]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase interactively]' \
            '--wallet-name=[Wallet identifier; defaults to the mnemonic fingerprint]: :' \
            '--network=[]:choice:(mainnet testnet signet regtest)' \
            '--backend=[]: :' \
            '--rpc-url=[]: :' \
            '--neutrino-url=[]: :' \
            '--directory=[]: :' \
            '--tor-socks-host=[Tor SOCKS host override]: :' \
            '--tor-socks-port=[Tor SOCKS port override]: :' \
            '--fee-rate=[Manual fee rate in sat/vB (mutually exclusive with --block-target). Required when the backend is neutrino.]: :' \
            '--block-target=[Target blocks for fee estimation (mutually exclusive with --fee-rate). Not supported with the neutrino backend.]: :' \
            '--min-confirmations=[Confirmations required before the next phase starts (0 disables gating). Defaults to the tumbler.min_confirmations_between_phases setting (6).]: :' \
            '--counterparties=[Override the counterparty count for every phase at runtime. Useful when the configured count is unavailable on the chosen network.]: :' \
            '--resume[Resume a plan that ended in a terminal state (FAILED, CANCELLED, or stuck-RUNNING). Completed phases are kept; all other phases are reset to PENDING and the runner picks up at the first non-completed phase. Has no effect on a plan that is already PENDING.]' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--config-file=[Config file path (decoupled from data dir). Defaults to <data-dir>/config.toml]:file:_files' \
            '--log-level=[]: :' \
            '--help[Show this message and exit]'
          ;;
        status)
          _arguments \
            '--wallet-name=[Wallet identifier; defaults to the mnemonic fingerprint]: :' \
            '--mnemonic-file=[Path to mnemonic file]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase interactively]' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--config-file=[Config file path (decoupled from data dir). Defaults to <data-dir>/config.toml]:file:_files' \
            '--log-level=[]: :' \
            '--help[Show this message and exit]'
          ;;
      esac
      ;;
  esac
}

compdef _jm_tumbler jm-tumbler
