#compdef jmwalletd

# Static completion for jmwalletd
# Generated by scripts/generate_completions.py

_jmwalletd() {
  _arguments \
    '--host=[Bind address]: :' \
    '--port=[HTTPS/HTTP port]: :' \
    '--ws-port=[WebSocket port (0 = same as HTTP)]: :' \
    '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
    '--config-file=[Config file path (decoupled from data dir). Defaults to <data-dir>/config.toml]:file:_files' \
    '--no-tls[Disable TLS (plain HTTP)]' \
    '--help[Show this message and exit]'
}

compdef _jmwalletd jmwalletd
