# Static completion for jmwalletd
# Generated by scripts/generate_completions.py

_jmwalletd_completion() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    COMPREPLY=( $(compgen -W "--help --host --port --ws-port --data-dir --config-file --no-tls" -- "$cur") )
    return 0
}

complete -o default -F _jmwalletd_completion jmwalletd
